// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAn9sDD-yukZEHMjsTt1YNoXoDWhY-9Ak',
    appId: '1:541368536795:web:9f3eef9916886e34ec86fe',
    messagingSenderId: '541368536795',
    projectId: 'lmsnsbm-403ea',
    authDomain: 'lmsnsbm-403ea.firebaseapp.com',
    storageBucket: 'lmsnsbm-403ea.appspot.com',
    measurementId: 'G-WZX76428WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGUpPzUBsN3Mt6r4dyZ_LqI6TI2hFqCQ',
    appId: '1:541368536795:android:27192f5a29b3929aec86fe',
    messagingSenderId: '541368536795',
    projectId: 'lmsnsbm-403ea',
    storageBucket: 'lmsnsbm-403ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSWKwxNS3pyCJgxZ7zNtgZyI0woQMFB3U',
    appId: '1:541368536795:ios:d969d88bb9dacf8bec86fe',
    messagingSenderId: '541368536795',
    projectId: 'lmsnsbm-403ea',
    storageBucket: 'lmsnsbm-403ea.appspot.com',
    iosClientId: '541368536795-l595b3v4al140dt0rdl5bhjndp59cjsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmsnsbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSWKwxNS3pyCJgxZ7zNtgZyI0woQMFB3U',
    appId: '1:541368536795:ios:d969d88bb9dacf8bec86fe',
    messagingSenderId: '541368536795',
    projectId: 'lmsnsbm-403ea',
    storageBucket: 'lmsnsbm-403ea.appspot.com',
    iosClientId: '541368536795-l595b3v4al140dt0rdl5bhjndp59cjsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmsnsbm',
  );
}
